FROM lscr.io/linuxserver/transmission:latest

LABEL org.opencontainers.image.source="https://github.com/x81k25/automatic-transmission-daemon"
LABEL org.opencontainers.image.description="Transmission BitTorrent client for ATD pipeline"
LABEL org.opencontainers.image.base.name="lscr.io/linuxserver/transmission:latest"
